# Generated by Django 4.2.11 on 2024-06-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emirate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_package', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FreezoneInEmirates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emirate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.emirate')),
                ('freezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.freezone')),
            ],
            options={
                'unique_together': {('freezone', 'emirate')},
            },
        ),
        migrations.CreateModel(
            name='BusinessInFreezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.businessactivity')),
                ('freezone_and_emirate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.freezoneinemirates')),
            ],
            options={
                'unique_together': {('freezone_and_emirate', 'business')},
            },
        ),
        migrations.CreateModel(
            name='VisaPackagesInBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_in_freezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.businessinfreezone')),
                ('visa_packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.visapackage')),
            ],
            options={
                'unique_together': {('business_in_freezone', 'visa_packages')},
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('establishment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('e_channel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('residence_visa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medical', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('business_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotation.businessactivity')),
                ('emirate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emirate_details', to='quotation.emirate')),
                ('freezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotation.freezone')),
                ('visa_packages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.visapackage')),
            ],
            options={
                'unique_together': {('freezone', 'business_activity', 'visa_packages')},
            },
        ),
    ]