# Generated by Django 4.2.11 on 2024-06-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emirates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FreezoneInEmirates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emirates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.emirates')),
                ('freezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.freezone')),
            ],
            options={
                'unique_together': {('freezone', 'emirates')},
            },
        ),
        migrations.CreateModel(
            name='FreezoneDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('establishment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('e_channel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('residence_visa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotation.businessactivity')),
                ('freezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotation.freezone')),
                ('visa_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotation.visapackage')),
            ],
            options={
                'unique_together': {('freezone', 'business_activity', 'visa_package')},
            },
        ),
        migrations.CreateModel(
            name='BusinessInFreezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.businessactivity')),
                ('emirates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.emirates')),
                ('freezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.freezone')),
            ],
            options={
                'unique_together': {('freezone', 'emirates', 'business')},
            },
        ),
    ]
