# Generated by Django 4.2.11 on 2024-06-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('establishment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('e_channel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('residence_visa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotation.businessactivity')),
            ],
        ),
        migrations.RenameField(
            model_name='businessinfreezone',
            old_name='emirates',
            new_name='emirate',
        ),
        migrations.RenameField(
            model_name='freezoneinemirates',
            old_name='emirates',
            new_name='emirate',
        ),
        migrations.AlterUniqueTogether(
            name='businessinfreezone',
            unique_together={('freezone', 'emirate', 'business')},
        ),
        migrations.AlterUniqueTogether(
            name='freezoneinemirates',
            unique_together={('freezone', 'emirate')},
        ),
        migrations.RenameModel(
            old_name='Emirates',
            new_name='Emirate',
        ),
        migrations.DeleteModel(
            name='FreezoneDetails',
        ),
        migrations.AddField(
            model_name='quotation',
            name='emirate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emirate_details', to='quotation.emirate'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='freezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotation.freezone'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='visa_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotation.visapackage'),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('freezone', 'business_activity', 'visa_package')},
        ),
    ]
