# Generated by Django 4.2.11 on 2024-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_logoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezone',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
