# Generated by Django 4.2.11 on 2024-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotation_rename_emirates_businessinfreezone_emirate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('freezone', 'business_activity')},
        ),
        migrations.AddField(
            model_name='quotation',
            name='number_of_visa_packages',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='visa_package',
        ),
        migrations.DeleteModel(
            name='VisaPackage',
        ),
    ]
