# Generated by Django 4.2.11 on 2024-06-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_freezone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezone',
            name='allowed_packages',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='freezone',
            name='compliance_details',
            field=models.TextField(default=''),
        ),
    ]
