# Generated by Django 4.2.11 on 2024-06-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotation_total_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessinfreezone',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='businessinfreezone',
            name='freezone_and_emirate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.freezoneinemirates'),
        ),
        migrations.AlterUniqueTogether(
            name='businessinfreezone',
            unique_together={('freezone_and_emirate', 'business')},
        ),
        migrations.RemoveField(
            model_name='businessinfreezone',
            name='emirate',
        ),
        migrations.RemoveField(
            model_name='businessinfreezone',
            name='freezone',
        ),
    ]
