# Generated by Django 4.2.11 on 2024-06-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_alter_businessinfreezone_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_package', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='number_of_visa_packages',
        ),
        migrations.CreateModel(
            name='VisaPackagesInBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_in_freezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.businessinfreezone')),
                ('visa_packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.visapackage')),
            ],
        ),
    ]
