# Generated by Django 4.2.11 on 2024-06-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_alter_quotation_e_channel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visapackagesinbusiness',
            unique_together={('business_in_freezone', 'visa_packages')},
        ),
    ]
