# Generated by Django 4.2.11 on 2024-06-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_alter_visapackagesinbusiness_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('freezone', 'business_activity', 'visa_packages')},
        ),
    ]
