# Generated by Django 4.2.11 on 2024-06-24 18:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customer_auth', '0003_customer_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, unique=True),
        ),
    ]
